### ISSUE TITLE
corrupt cache

### ISSUE THREAD

**Issue by AudreyBeard** [SU-ECE-17-7/hotspotter#12]
Issue in **master**: *fatal io error*

Eddy and Taz encountered an issue with the **fileio** package, which Eddy contributes to the prior existence of **.hotspotter**, the cache of the previous session.

Eddy's dirty fix: between sessions, `rm -Rf .hotspotter`

From Taz from Eddy:
"One step missing from setup that everyone participated in without noting. This is because Eddy followed the documentation, but couldn't make it work"

**Comment by AudreyBeard** [comment]
Eddy believes this is an issue for Matt to look at

**Comment by cheisterkamp** [comment]
'
=============================
[cc2] Precomputing chips and loading chip paths: 'test3'
=============================
[cc2] chip_uid = '_CHIP(sz750)'
[parallel] Already computed 0 compute_chip tasks

tic('Executing 1 compute_chip:  tasks in serial')
compute_chip: 
compute_chip: 1/1
...toc('Executing 1 compute_chip:  tasks in serial')=0.1419s
[cc2] Done Precomputing chips and loading chip paths
[cc2]=============================
[back] layout_figures
[df2] Presenting figures...
[inter] starting image interaction
[**back] query(cid=None)
[**back.query()] cx = 0)

====================
[hs] query database
====================
[mc3] FEAT_UID is different. Need to reload features
[mc3] Old: None
[mc3] New: _FEAT(hesaff+sift,0_9001)_CHIP(sz750)
[hs] unload_cxdata(cx='all')
[hs] Unloading all data
[hs] finished unloading all data

=============================
[cc2] Precomputing chips and loading chip paths: 'test3'
=============================
[cc2] chip_uid = '_CHIP(sz750)'
[parallel] Already computed 1 compute_chip tasks

tic('Executing 1 compute_chip:  tasks in serial')
compute_chip: 
compute_chip: 1/1
...toc('Executing 1 compute_chip:  tasks in serial')=0.1188s
[cc2] Done Precomputing chips and loading chip paths
[cc2]=============================

=============================
[fc2] Precomputing and loading features: 'test3'
=============================
[fc2] feat_uid = '_FEAT(hesaff+sift,0_9001)_CHIP(sz750)'
[io] fname='kpts_list_FEAT(hesaff+sift,0_9001)_CHIP(sz750)_cids((2,)n$v}8c%~).npy' does not exist
[io] fname='desc_list_FEAT(hesaff+sift,0_9001)_CHIP(sz750)_cids((2,)n$v}8c%~).npy' does not exist
[fc2]  Loading _FEAT(hesaff+sift,0_9001)_CHIP(sz750) individually
[parallel] Already computed 0 precompute_hesaff tasks

tic('Distributing 2 precompute_hesaff:  tasks to 2 processes')
precompute_hesaff: 
^Cpython: Fatal IO error 0 (Success) on X server :0.
python: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
precompute_hesaff: 2/2Caught ctrl+cCaught ctrl+c'

**Comment by cheisterkamp** [comment]
Here's an example of the error before and after doing 
'rm -Rf ~/.hotspotter/'

'noah@noah-VirtualBox:~/code/hotspotter$ python main.py 
[common] not profiling.
using: '/home/noah/code/hotspotter/hstpl/extern_feat/libhesaff.so'
[extern_feat] new hessaff is available
[extern_feat] old hessaff is available
[extern_feat] using: new pyhesaff
[helpers] * Reading text file: 'cached_dir_db_dir.txt' 
[main] trying to read db_dir from cache: '/home/noah/Desktop/test3'
[hs] load preferences
[hs] defaulting preferences
[hs] Able to load prefs? ...False
[hs][pref] fpath='/home/noah/.hotspotter/global_cache/prefs' does not exist
[hs] defaulting preferences
[hs] load()
[hs] Unloading all data
[hs] finished unloading all data

=============================
[ld2] Loading hotspotter csv tables: '/home/noah/Desktop/test3'
=============================
[ld2] isCurrentVersion=True
[ld2] detected 'current'
-------------------------
[ld2] Loading database tables: 
[ld2] Loading name table: '/home/noah/Desktop/test3/_hsdb/name_table.csv'
[ld2] * Loaded 0 names (excluding unknown names)
[ld2] * Done loading name table
[ld2] Loading images
[ld2] * Loading image table: '/home/noah/Desktop/test3/_hsdb/image_table.csv'
[ld2] * table specified 0 images
[ld2] * Loading image directory: '/home/noah/Desktop/test3/images'
[ld2] * dir specified 10 images
[ld2] * 0 were already specified in the table
[ld2] * Loaded 10 images
[ld2] * Done loading images
[ld2] Loading chip table: '/home/noah/Desktop/test3/_hsdb/chip_table.csv'
[ld2] * num_chips: -1
[ld2] * chip_csv_format: ['ChipID', 'ImgID', 'NameID', 'roi[tl_x  tl_y  w  h]', 'theta'] 
[ld2] * num_user_properties: 0
[ld2] * Loaded: 0 chips
[ld2] * Done loading chip table
[ld2] Done Loading hotspotter csv tables: '/home/noah/Desktop/test3'
[hs] update_samples():
[hs] * default: all chips in training

=============================
[cc2] Precomputing chips and loading chip paths: 'test3'
=============================
[cc2] chip_uid = '_CHIP(sz750)'

=============================
[fc2] Precomputing and loading features: 'test3'
=============================
[fc2] feat_uid = '_FEAT(hesaff+sift,0_9001)_CHIP(sz750)'
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    hs = main(defaultdb=None, usedbcache=True)
  File "main.py", line 133, in main
    from hotspotter import fileio as io
ImportError: cannot import name fileio
noah@noah-VirtualBox:~/code/hotspotter$ rm -Rf ~/.hotspotter/
noah@noah-VirtualBox:~/code/hotspotter$ python main.py 
[common] not profiling.
[helpers] mkdir('/home/noah/.hotspotter/global_cache')
using: '/home/noah/code/hotspotter/hstpl/extern_feat/libhesaff.so'
[extern_feat] new hessaff is available
[extern_feat] old hessaff is available
[extern_feat] using: new pyhesaff
[main] trying to read db_dir from cache: None
[hs] load preferences
[hs] defaulting preferences
[hs] Able to load prefs? ...False
[hs][pref] fpath='/home/noah/.hotspotter/global_cache/prefs' does not exist
[hs] defaulting preferences
[hs] load()
[hs] Unloading all data
[hs] finished unloading all data
[main] ValueError = ValueError('db_dir=None does not exist!',)
[common] [df2] current backend is: u'Qt4Agg'
[common] [df2] matplotlib.use(Qt4Agg)
main.py
[*guitools] Initializing QApplication
[front] stealing standard out
[*back] connect_api()
[back] layout_figures
[df2] Presenting figures...
[*guitools] setting active window
[*guitools] running core application loop.'

**Comment by mattdioso** [comment]
In main.py, line 133 change:
from hotspotter import fileio as io
to:
from hscom import fileio as io
