### ISSUE TITLE
QPixMap Error

### ISSUE THREAD

**Issue by AudreyBeard** [SU-ECE-17-7/hotspotter#20]
# To Reproduce

1. Start importing images
2. While in directory explorer window, click CANCEL
3. Import images by directory
4. **Click on an image to see it**
5. Run autochip
6. **Click on a chip to see it**

**Error occurs at these steps**

**Comment by mattdioso** [comment]
Need matplotlib version 1.3.1

`sudo pip uninstall matplotlib;
sudo pip install matplotlib==1.3.1`

alternatively:
`sudo apt-get uninstall python-matplotlib;
sudo apt-get install python-matplotlib`
